# Generated by Django 3.2.12 on 2025-09-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(choices=[('B', 'Бизнес'), ('P', 'Личное'), ('T', 'Налог')], max_length=200),
        ),
    ]
