# Generated by Django 4.2.24 on 2025-09-29 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_alter_status_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='title',
        ),
        migrations.AddField(
            model_name='status',
            name='val',
            field=models.CharField(default=1, max_length=100, verbose_name='Статусы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='flow.status'),
        ),
    ]
