# Generated by Django 4.2.24 on 2025-09-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_remove_status_title_status_val_alter_field_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='val',
            field=models.CharField(default='Bussiness', max_length=100, verbose_name='Статусы'),
        ),
    ]
