# Generated by Django 3.2.12 on 2025-09-30 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_alter_status_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='field',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.status', verbose_name='Категория ДДС'),
        ),
        migrations.AlterField(
            model_name='status',
            name='val',
            field=models.CharField(max_length=100, verbose_name='Наименование статуса'),
        ),
    ]
