# Generated by Django 3.2.12 on 2025-09-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_auto_20250930_0505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': 'Запись ДДС', 'verbose_name_plural': 'Записи ДДС'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterField(
            model_name='status',
            name='val',
            field=models.CharField(choices=[('Бизнес', 'Бизнес'), ('Личное', 'Личное'), ('Налоги', 'Налоги')], max_length=100, verbose_name='Наименование статуса'),
        ),
    ]
