# Generated by Django 4.2.24 on 2025-10-03 10:46

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0006_remove_subcategory_category_alter_subcategory_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_subcategory', to='flow.category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='value',
            field=models.CharField(choices=[('VPS', 'VPS'), ('Proxy', 'Proxy'), ('Farpost', 'Farpost'), ('Avito', 'Avito')], default=1, max_length=100, unique=True, verbose_name='Подкатегория'),
            preserve_default=False,
        ),
    ]
