# Generated by Django 4.2.24 on 2025-10-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0008_alter_subcategory_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='value',
            field=models.CharField(choices=[('VPS', 'VPS'), ('Proxy', 'Proxy'), ('Farpost', 'Farpost'), ('Avito', 'Avito')], max_length=100, unique=True, verbose_name='Подкатегория'),
        ),
    ]
