# Generated by Django 4.2.24 on 2025-10-03 19:15

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0009_alter_subcategory_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='flow.category'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
