# Generated by Django 4.2.24 on 2025-10-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0010_remove_post_subcategory_alter_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='value',
            field=models.CharField(choices=[('Инфраструктура', 'Инфраструктура'), ('Маркетинг', 'Маркетинг'), ('VPS', 'VPS'), ('Proxy', 'Proxy'), ('Farpost', 'Farpost'), ('Avito', 'Avito')], max_length=100, unique=True, verbose_name='Категория'),
        ),
    ]
