# Generated by Django 4.2.24 on 2025-10-03 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0011_alter_category_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_subcategory', to='flow.category', verbose_name='Подкатегория'),
            preserve_default=False,
        ),
    ]
