# Generated by Django 3.2.12 on 2025-09-30 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0011_alter_status_val'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['pub_date'], 'verbose_name': 'Запись ДДС', 'verbose_name_plural': 'Записи ДДС'},
        ),
    ]
