# Generated by Django 3.2.12 on 2025-09-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0012_alter_field_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='val',
            field=models.CharField(choices=[('Бизнес', 'B'), ('Личное', 'P'), ('Налоги', 'T')], max_length=100, unique=True, verbose_name='Наименование статуса'),
        ),
    ]
