# Generated by Django 3.2.12 on 2025-09-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0013_alter_status_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='val',
            field=models.CharField(choices=[('1', 'Бизнес'), ('2', 'Личное'), ('3', 'Налоги')], max_length=100, unique=True, verbose_name='Наименование статуса'),
        ),
    ]
