# Generated by Django 4.2.24 on 2025-10-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0013_category_slug_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='value',
            field=models.CharField(max_length=100, unique=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='flowtype',
            name='value',
            field=models.CharField(max_length=100, unique=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='status',
            name='value',
            field=models.CharField(max_length=100, unique=True, verbose_name='Статус'),
        ),
    ]
