# Generated by Django 3.2.12 on 2025-09-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0016_alter_status_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='val',
            field=models.CharField(choices=[('Бизнес', 'Бизнес'), ('Личное', 'Личное'), ('Налоги', 'Налоги')], max_length=100, unique=True, verbose_name='Наименование статуса'),
        ),
    ]
