# Generated by Django 4.2.24 on 2025-10-10 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0016_remove_category_level_remove_category_lft_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlowType',
            new_name='Type',
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['value', 'category'], 'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Пождкатегории'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='flow_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories_type', to='flow.type', verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.TextField(blank=True, max_length=906, verbose_name='Комментарий (необязательно)'),
        ),
    ]
