# Generated by Django 3.2.12 on 2025-09-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0017_alter_status_val'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True, verbose_name='Наименование нового статуса')),
            ],
        ),
        migrations.RenameField(
            model_name='status',
            old_name='val',
            new_name='value',
        ),
    ]
