# Generated by Django 3.2.12 on 2025-09-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0018_auto_20250930_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
