# Generated by Django 3.2.12 on 2025-09-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0019_alter_field_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomStatus',
        ),
        migrations.AlterField(
            model_name='field',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
