# Generated by Django 3.2.12 on 2025-09-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0020_auto_20250930_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
