# Generated by Django 3.2.12 on 2025-09-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0021_alter_field_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
