# Generated by Django 4.2.24 on 2025-10-01 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0024_alter_field_pub_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Field',
            new_name='Table',
        ),
    ]
