# Generated by Django 4.2.24 on 2025-10-01 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0027_alter_table_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='Post',
        ),
    ]
