# Generated by Django 4.2.24 on 2025-10-01 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0028_rename_table_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pub_date'], 'verbose_name': 'Запись о ДДС', 'verbose_name_plural': 'Записи о ДДС'},
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='flow.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='status',
            name='value',
            field=models.CharField(choices=[('Бизнес', 'Бизнес'), ('Личное', 'Личное'), ('Налоги', 'Налоги')], max_length=100, unique=True, verbose_name='Статус'),
        ),
    ]
