# Generated by Django 4.2.24 on 2025-10-01 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0029_alter_post_options_alter_post_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_status', to='flow.status', verbose_name='Статус'),
        ),
    ]
